import { createOpenAI } from "@ai-sdk/openai";
import { generateObject, generateText } from "ai";
import zod from "zod";
import { Ingredient } from "../lib/types";

export function createGitHubModels() {
  const githubToken = process.env.GITHUB_TOKEN;
  if (!githubToken) {
    throw new Error("GitHub token not configured");
  }

  return createOpenAI({
    apiKey: githubToken,
    baseURL: "https://models.github.ai/inference",
  });
}

export async function generateRecipeTags({
  name,
  ingredients,
}: {
  name?: string;
  ingredients: Ingredient[];
}): Promise<string[]> {
  const githubModels = createGitHubModels();
  const systemPrompt = `You are an expert cocktail sommelier. Generate a list of relevant tags for a cocktail recipe based on its ingredients and name.
  Guidelines:
  - Focus on flavor profiles, ingredients, and cocktail types
  - Keep it concise, 3-5 tags maximum
  - Avoid generic tags like "cocktail" or "drink"
  - Use lowercase, no spaces, separate with commas
  - Do not include the name of the cocktail in the tags`;

  const userPrompt = `Generate tags for a cocktail recipe with these ingredients: ${ingredients
    .map((ing) => `${ing.amount} ${ing.unit} ${ing.name}`)
    .join(", ")}${name ? ` and name "${name}"` : ""}`;

  const result = await generateObject({
    model: githubModels(process.env.CHAT_MODEL || "openai/gpt-4.1-nano"),
    system: systemPrompt,
    prompt: userPrompt,
    schema: zod.object({
      tags: zod.array(zod.string().min(1)),
    }),
  });

  if (!result && !result.object) {
    console.warn("No tags generated by LLM");
  }
  return result.object.tags;
}

export async function generateRecipeDescription({
  ingredients,
  name,
}: {
  ingredients: Ingredient[];
  name?: string;
}): Promise<string> {
  const githubModels = createGitHubModels();
  // Create ingredient list for prompt
  const ingredientsList = ingredients
    .map((ing) => `${ing.amount} ${ing.unit} ${ing.name}`)
    .join(", ");

  // Create system prompt for description generation
  const systemPrompt = `You are an expert cocktail sommelier and writer. Generate a simple description for a cocktail based on its ingredients. 

Guidelines:
- Focus on flavor profiles rather than exact measurements
- Highlight the most interesting or premium ingredients
- Keep it to 1-2 sentences maximum
- Do not be verbose. Be concise.
- Don't mention specific amounts or measurements
- Make it sound appealing and interesting
- DO NOT make it sound pretentious.
- Don't include the name of the cocktail in the description`;

  const userPrompt = `Create a description for a cocktail${
    name ? ` called "${name}"` : ""
  } with these ingredients: ${ingredientsList}`;

  const result = await generateText({
    model: githubModels(process.env.CHAT_MODEL || "openai/gpt-4.1-nano"),
    system: systemPrompt,
    prompt: userPrompt,
    maxTokens: 150,
    temperature: 0.9, // Add some creativity
  });

  return result.text.trim();
}
